[package]
name = "lb_pair"
version = "0.1.0"
edition = "2021"
exclude = [
  # Those files are contract-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "schema"
path = "schema/schema.rs" # Adjust the path according to your project structure


[features]
default = ["schema"]
schema = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = [
  "liquidity_book_impl",
] }
schemars = "0.8.16"
serde = { version = "1.0" }
serde_json = "1"
serde-json-wasm = { version = "1.0" }
cosmwasm-schema = "1.5"
thiserror = { version = "1.0" }
ethnum = { version = "1.5" }

[dev-dependencies]
anyhow = "1"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.11" }
shade-multi-test = { path = "../../../packages/multi_test", features = [
  "admin",
  "lb_pair",
  "lb_token",
  "snip20",
] }
