[package]
name = "wynd-lend-market"
version = { workspace = true }
authors = ["Jakub Bogucki <jakub@confio.gmbh>"]
edition = { workspace = true }
description = "Implementation of Market contract"
repository = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
wyndex-oracle = { workspace = true }
wynd-lend-token = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
utils = { workspace = true }
wyndex = { workspace = true }
wyndex-multi-hop = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
wyndex-tests = { workspace = true }